# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RnoaJqFnBxoztOYqJ5A88HN5ZYbfCuY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""# LOAD DATASET"""

credit_card_data=pd.read_csv("/content/sample_data/creditcard.csv")
credit_card_data

credit_card_data.info()

credit_card_data.Class.value_counts()

"""# BALANCING THE HIGHLY UNBALANCED DATASET"""

legit=credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]

"""# STATISTICAL MEASURES OF THE DATA"""

legit.Amount.describe()

fraud.Amount.describe()

credit_card_data.groupby('Class').mean()

"""
# UNDERSAMPLING (RANDOM SAMPLING)
---

"""

legit_sample=legit.sample(n=492)

new_dataset=pd.concat([legit_sample,fraud],axis=0)
new_dataset

new_dataset.value_counts('Class')

"""#SPLITTING FEATURES & TARGET"""

x=new_dataset.drop(columns='Class',axis=1)
y=new_dataset['Class']

"""#TRAIN TEST SPLIT"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=42)

"""# MODEL TRAINING (LOGISTIC REGRESSION)"""

model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

accuracy_score(y_pred,y_test)

